# general settings
name: SWSformer-AllWeatherNight-snow
model_type: ImageRestorationModel
scale: 1
num_gpu: 1
manual_seed: 1111

datasets:
  train:
    name: AllWeatherNight
    type: PairedImageDataset
    dataroot_gt: ./datasets/AllWeatherNight/train/snow_scene_gt
    dataroot_lq: ./datasets/AllWeatherNight/train/snow_scene

    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 256
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 6
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: AllWeatherNight
    type: PairedImageDataset
    dataroot_gt: ./datasets/AllWeatherNight/test/snow_scene_gt
    dataroot_lq: ./datasets/AllWeatherNight/test/snow_scene
    io_backend:
      type: disk

network_g:
  type: SWSformer
  width: 32
  enc_blk_nums: [2, 2, 4, 8]
  middle_blk_num: 12
  dec_blk_nums: [2, 2, 2, 2]
  win_size: 8
  sub_win_size: 8
  nwc_ks: [3, 3, 3, 3, 3]
  qkv_bias: True

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 1e-3
    weight_decay: 0.
    betas: [0.9, 0.9]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 16680
    eta_min: !!float 1e-7

  total_iter: 16680
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: PSNRLoss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  val_freq: !!float 16681
  save_img: false
  use_image: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 417
  save_checkpoint_freq: 16681
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
