# general settings
name: SWSformerMH-GoPro
model_type: MultiHeadImageRestorationModel
scale: 1
num_gpu: 1
manual_seed: 1111

datasets:
  train:
    name: gopro-train
    type: PairedImageDataset
    dataroot_gt: ./datasets/GoPro/train/sharp_crops.lmdb
    dataroot_lq: ./datasets/GoPro/train/blur_crops.lmdb

    filename_tmpl: '{}'
    io_backend:
      type: lmdb

    gt_size: 256
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 6
    dataset_enlarge_ratio: 1
    prefetch_mode: ~
    
  val:
    name: gopro-test
    type: PairedImageDataset
    dataroot_gt: ./datasets/GoPro/test/target.lmdb
    dataroot_lq: ./datasets/GoPro/test/input.lmdb

    io_backend:
      type: lmdb

network_g:
  type: SWSformerMH
  width: 64
  enc_blk_nums: [2, 2, 4, 8]
  middle_blk_num: 12
  dec_blk_nums: [2, 2, 2, 2]
  win_size: 16
  sub_win_size: 8
  nwc_ks: [7, 5, 3, 3, 3]
  qkv_bias: True
  n_heads: 4
  combinate_heads: true

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 1e-3
    weight_decay: 0.
    betas: [0.9, 0.9]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 112160
    eta_min: !!float 1e-7

  total_iter: 112160
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: MultiHeadPSNRLoss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  val_freq: 112161
  save_img: false


  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr_mh
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim_mh
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 2804
  save_checkpoint_freq: 112161
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
